import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import AppLayout from "../layouts/AppLayout";
import { getQuizQuestions } from "../services/quizService";
import { settings } from "../config/settings";

export default function QuizGame() {
  const navigate = useNavigate();

    // Create quiz only once
      const [quizQuestions] = useState(() => getQuizQuestions());

        const [currentQuestion, setCurrentQuestion] = useState(0);
          const [selectedAnswer, setSelectedAnswer] = useState<number | null>(null);
            const [score, setScore] = useState(0);
              const [timeLeft, setTimeLeft] = useState(settings.timerSeconds);

                useEffect(() => {
                    if (timeLeft <= 0) {
                          navigate("/result", {
                                  state: {
                                            score,
                                                      total: quizQuestions.length,
                                                              },
                                                                    });
                                                                          return;
                                                                              }

                                                                                  const timer = setInterval(() => {
                                                                                        setTimeLeft((prev) => prev - 1);
                                                                                            }, 1000);

                                                                                                return () => clearInterval(timer);
                                                                                                  }, [timeLeft, navigate, score, quizQuestions]);

                                                                                                    function nextQuestion() {
                                                                                                        let newScore = score;

                                                                                                            if (
                                                                                                                  selectedAnswer ===
                                                                                                                        quizQuestions[currentQuestion].answer
                                                                                                                            ) {
                                                                                                                                  newScore++;
                                                                                                                                        setScore(newScore);
                                                                                                                                            }

                                                                                                                                                if (currentQuestion === quizQuestions.length - 1) {
                                                                                                                                                      navigate("/result", {
                                                                                                                                                              state: {
                                                                                                                                                                        score: newScore,
                                                                                                                                                                                  total: quizQuestions.length,
                                                                                                                                                                                          },
                                                                                                                                                                                                });
                                                                                                                                                                                                      return;
                                                                                                                                                                                                          }

                                                                                                                                                                                                              setSelectedAnswer(null);
                                                                                                                                                                                                                  setCurrentQuestion((prev) => prev + 1);
                                                                                                                                                                                                                    }

                                                                                                                                                                                                                      return (
                                                                                                                                                                                                                          <AppLayout title="Quiz">
                                                                                                                                                                                                                                <div
                                                                                                                                                                                                                                        style={{
                                                                                                                                                                                                                                                  padding: "20px",
                                                                                                                                                                                                                                                            maxWidth: "600px",
                                                                                                                                                                                                                                                                      margin: "0 auto",
                                                                                                                                                                                                                                                                              }}
                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                            <h2 style={{ textAlign: "center" }}>
                                                                                                                                                                                                                                                                                                      Question {currentQuestion + 1} / {quizQuestions.length}
                                                                                                                                                                                                                                                                                                              </h2>

                                                                                                                                                                                                                                                                                                                      <h1
                                                                                                                                                                                                                                                                                                                                style={{
                                                                                                                                                                                                                                                                                                                                            color: "red",
                                                                                                                                                                                                                                                                                                                                                        textAlign: "center",
                                                                                                                                                                                                                                                                                                                                                                    marginTop: "20px",
                                                                                                                                                                                                                                                                                                                                                                              }}
                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                {timeLeft}s
                                                                                                                                                                                                                                                                                                                                                                                                        </h1>

                                                                                                                                                                                                                                                                                                                                                                                                                <p
                                                                                                                                                                                                                                                                                                                                                                                                                          style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                      fontSize: "22px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                  fontWeight: "bold",
                                                                                                                                                                                                                                                                                                                                                                                                                                                              marginTop: "30px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          marginBottom: "30px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {quizQuestions[currentQuestion].question}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {quizQuestions[currentQuestion].options.map(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                (option, index) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          key={index}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onClick={() => setSelectedAnswer(index)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      display: "block",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      margin: "10px 0",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      padding: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      backgroundColor:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        selectedAnswer === index
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ? "#ff5722"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                : "#f5f5f5",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                color:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  selectedAnswer === index
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ? "white"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          : "black",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          border: "1px solid #ccc",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          borderRadius: "8px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          cursor: "pointer",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          fontSize: "16px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {option}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onClick={nextQuestion}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            disabled={selectedAnswer === null}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  marginTop: "30px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          padding: "14px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      backgroundColor:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    selectedAnswer === null
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ? "#cccccc"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    : "#ff5722",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                color: "white",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            border: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        borderRadius: "8px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fontSize: "18px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cursor:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              selectedAnswer === null
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ? "not-allowed"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              : "pointer",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {currentQuestion === quizQuestions.length - 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ? "Finish Quiz"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  : "Next Question"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </AppLayout>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }