import { useState } from "react";
import AppLayout from "../layouts/AppLayout";
import { getSettings, saveSettings } from "../services/settingsService";

export default function BusinessSettings() {
  const current = getSettings();

    const [rewardPrice, setRewardPrice] = useState(current.menuPrice);
      const [timer, setTimer] = useState(current.timerSeconds);
        const [cooldown, setCooldown] = useState(current.cooldownMinutes);
          const [passingScore, setPassingScore] = useState(current.requiredScore);
            const [questionsPerQuiz, setQuestionsPerQuiz] = useState(
                current.questionsPerQuiz
                  );
                    const [quizEnabled, setQuizEnabled] = useState(current.quizEnabled);
                      const [upiId, setUpiId] = useState(current.upiId);

                        function handleSave() {
                            saveSettings({
                                  ...current,
                                        menuPrice: rewardPrice,
                                              timerSeconds: timer,
                                                    cooldownMinutes: cooldown,
                                                          requiredScore: passingScore,
                                                                questionsPerQuiz,
                                                                      quizEnabled,
                                                                            upiId,
                                                                                });

                                                                                    alert("Settings saved successfully.");
                                                                                      }

                                                                                        return (
                                                                                            <AppLayout title="Business Settings">
                                                                                                  <div style={{ padding: "20px" }}>
                                                                                                          <h2>Business Settings</h2>

                                                                                                                  <label>Churmuri Price (₹)</label>
                                                                                                                          <input
                                                                                                                                    type="number"
                                                                                                                                              value={rewardPrice}
                                                                                                                                                        onChange={(e) => setRewardPrice(Number(e.target.value))}
                                                                                                                                                                  style={{
                                                                                                                                                                              width: "100%",
                                                                                                                                                                                          padding: "12px",
                                                                                                                                                                                                      marginBottom: "20px",
                                                                                                                                                                                                                }}
                                                                                                                                                                                                                        />

                                                                                                                                                                                                                                <label>Quiz Timer (Seconds)</label>
                                                                                                                                                                                                                                        <input
                                                                                                                                                                                                                                                  type="number"
                                                                                                                                                                                                                                                            value={timer}
                                                                                                                                                                                                                                                                      onChange={(e) => setTimer(Number(e.target.value))}
                                                                                                                                                                                                                                                                                style={{
                                                                                                                                                                                                                                                                                            width: "100%",
                                                                                                                                                                                                                                                                                                        padding: "12px",
                                                                                                                                                                                                                                                                                                                    marginBottom: "20px",
                                                                                                                                                                                                                                                                                                                              }}
                                                                                                                                                                                                                                                                                                                                      />

                                                                                                                                                                                                                                                                                                                                              <label>Cooldown (Minutes)</label>
                                                                                                                                                                                                                                                                                                                                                      <input
                                                                                                                                                                                                                                                                                                                                                                type="number"
                                                                                                                                                                                                                                                                                                                                                                          value={cooldown}
                                                                                                                                                                                                                                                                                                                                                                                    onChange={(e) => setCooldown(Number(e.target.value))}
                                                                                                                                                                                                                                                                                                                                                                                              style={{
                                                                                                                                                                                                                                                                                                                                                                                                          width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                      padding: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                  marginBottom: "20px",
                                                                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                    />

                                                                                                                                                                                                                                                                                                                                                                                                                                                            <label>Passing Score</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              type="number"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        value={passingScore}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onChange={(e) => setPassingScore(Number(e.target.value))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    padding: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                marginBottom: "20px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <label>Questions Per Quiz</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            type="number"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      value={questionsPerQuiz}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onChange={(e) =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            setQuestionsPerQuiz(Number(e.target.value))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        padding: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    marginBottom: "20px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <label>UPI ID</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                type="text"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          value={upiId}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onChange={(e) => setUpiId(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              placeholder="yourupi@upi"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                padding: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            marginBottom: "20px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <label
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            display: "block",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        marginBottom: "20px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                type="checkbox"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            checked={quizEnabled}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onChange={(e) => setQuizEnabled(e.target.checked)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />{" "}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Quiz Enabled
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </label>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onClick={handleSave}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        padding: "14px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    background: "#F57C00",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                color: "white",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            border: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        borderRadius: "10px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fontSize: "18px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Save Settings
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </AppLayout>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }