import { useNavigate } from "react-router-dom";
import AppLayout from "../layouts/AppLayout";
import { getPaymentDetails } from "../services/paymentService";

export default function Payment() {
  const navigate = useNavigate();

    const payment = getPaymentDetails();

      return (
          <AppLayout title="Payment">
                <div
                        style={{
                                  padding: "20px",
                                            maxWidth: "500px",
                                                      margin: "0 auto",
                                                              }}
                                                                    >
                                                                            <h2
                                                                                      style={{
                                                                                                  textAlign: "center",
                                                                                                              color: "#d32f2f",
                                                                                                                        }}
                                                                                                                                >
                                                                                                                                          Payment Required
                                                                                                                                                  </h2>

                                                                                                                                                          <div
                                                                                                                                                                    style={{
                                                                                                                                                                                background: "#fff",
                                                                                                                                                                                            padding: "20px",
                                                                                                                                                                                                        borderRadius: "10px",
                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                    <h3>Churmuri</h3>

                                                                                                                                                                                                                                              <h1
                                                                                                                                                                                                                                                          style={{
                                                                                                                                                                                                                                                                        color: "#F57C00",
                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                          {payment.currency}
                                                                                                                                                                                                                                                                                                                      {payment.amount}
                                                                                                                                                                                                                                                                                                                                </h1>

                                                                                                                                                                                                                                                                                                                                          <hr />

                                                                                                                                                                                                                                                                                                                                                    <h3>UPI ID</h3>

                                                                                                                                                                                                                                                                                                                                                              <h2>{payment.upiId}</h2>

                                                                                                                                                                                                                                                                                                                                                                        <p>
                                                                                                                                                                                                                                                                                                                                                                                    Scan the QR code at the cart or pay using the UPI ID above.
                                                                                                                                                                                                                                                                                                                                                                                              </p>

                                                                                                                                                                                                                                                                                                                                                                                                        <hr />

                                                                                                                                                                                                                                                                                                                                                                                                                  <p>
                                                                                                                                                                                                                                                                                                                                                                                                                              Cash payment is also accepted.
                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onClick={() => navigate("/")}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    marginTop: "30px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                padding: "14px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            background: "#F57C00",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        color: "white",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    border: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                borderRadius: "10px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fontSize: "18px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Back to Home
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </AppLayout>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }