import { useNavigate } from "react-router-dom";
import AppLayout from "../layouts/AppLayout";
import { getSettings } from "../services/settingsService";

export default function Payment() {
  const navigate = useNavigate();
    const settings = getSettings();

      // Temporary until configurable from Owner Console
        const rewardItem = "Churmuri";
          const upiId = "yourupi@upi";

            return (
                <AppLayout title="Payment">
                      <div
                              style={{
                                        padding: "20px",
                                                  maxWidth: "500px",
                                                            margin: "0 auto",
                                                                    }}
                                                                          >
                                                                                  <h2 style={{ textAlign: "center", color: "#d32f2f" }}>
                                                                                            Payment Required
                                                                                                    </h2>

                                                                                                            <div
                                                                                                                      style={{
                                                                                                                                  background: "#fff",
                                                                                                                                              padding: "20px",
                                                                                                                                                          borderRadius: "10px",
                                                                                                                                                                      marginTop: "20px",
                                                                                                                                                                                }}
                                                                                                                                                                                        >
                                                                                                                                                                                                  <p><strong>Item</strong></p>
                                                                                                                                                                                                            <h3>{rewardItem}</h3>

                                                                                                                                                                                                                      <p style={{ marginTop: "20px" }}>
                                                                                                                                                                                                                                  <strong>Amount</strong>
                                                                                                                                                                                                                                            </p>

                                                                                                                                                                                                                                                      <h1 style={{ color: "#F57C00" }}>
                                                                                                                                                                                                                                                                  {settings.currency}
                                                                                                                                                                                                                                                                              {settings.menuPrice}
                                                                                                                                                                                                                                                                                        </h1>

                                                                                                                                                                                                                                                                                                  <hr />

                                                                                                                                                                                                                                                                                                            <p>
                                                                                                                                                                                                                                                                                                                        <strong>UPI ID</strong>
                                                                                                                                                                                                                                                                                                                                  </p>

                                                                                                                                                                                                                                                                                                                                            <h3>{upiId}</h3>

                                                                                                                                                                                                                                                                                                                                                      <p style={{ color: "#666" }}>
                                                                                                                                                                                                                                                                                                                                                                  Scan the QR code at the cart or pay using the UPI ID above.
                                                                                                                                                                                                                                                                                                                                                                            </p>

                                                                                                                                                                                                                                                                                                                                                                                      <hr />

                                                                                                                                                                                                                                                                                                                                                                                                <h3>Cash Payment</h3>

                                                                                                                                                                                                                                                                                                                                                                                                          <p>You can also pay directly at the counter.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                          <button
                                                                                                                                                                                                                                                                                                                                                                                                                                    onClick={() => navigate("/")}
                                                                                                                                                                                                                                                                                                                                                                                                                                              style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                          width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      marginTop: "30px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  padding: "14px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              background: "#F57C00",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          color: "white",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      border: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  borderRadius: "10px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              fontSize: "18px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Back to Home
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </AppLayout>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }