import { useState } from "react";
import { useNavigate } from "react-router-dom";
import AppLayout from "../layouts/AppLayout";

export default function Quiz() {
  const navigate = useNavigate();

    const [name, setName] = useState("");
      const [mobile, setMobile] = useState("");
        const [agree, setAgree] = useState(false);

          function handleContinue() {
              if (name.trim().length < 3) {
                    alert("Please enter your name.");
                          return;
                              }

                                  if (!/^[0-9]{10}$/.test(mobile)) {
                                        alert("Enter a valid 10-digit mobile number.");
                                              return;
                                                  }

                                                      if (!agree) {
                                                            alert("Please accept the WhatsApp consent.");
                                                                  return;
                                                                      }

                                                                          navigate("/play");
                                                                            }

                                                                              return (
                                                                                  <AppLayout title="Quiz Registration">
                                                                                        <div style={{ padding: "20px" }}>
                                                                                                <h2>Quiz Registration</h2>

                                                                                                        <label>Name</label>

                                                                                                                <input
                                                                                                                          type="text"
                                                                                                                                    value={name}
                                                                                                                                              onChange={(e) => setName(e.target.value)}
                                                                                                                                                        placeholder="Enter your name"
                                                                                                                                                                  style={{
                                                                                                                                                                              width: "100%",
                                                                                                                                                                                          padding: "12px",
                                                                                                                                                                                                      marginTop: "8px",
                                                                                                                                                                                                                  marginBottom: "18px",
                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                    />

                                                                                                                                                                                                                                            <label>Mobile Number</label>

                                                                                                                                                                                                                                                    <input
                                                                                                                                                                                                                                                              type="tel"
                                                                                                                                                                                                                                                                        value={mobile}
                                                                                                                                                                                                                                                                                  onChange={(e) => setMobile(e.target.value)}
                                                                                                                                                                                                                                                                                            placeholder="10-digit mobile number"
                                                                                                                                                                                                                                                                                                      style={{
                                                                                                                                                                                                                                                                                                                  width: "100%",
                                                                                                                                                                                                                                                                                                                              padding: "12px",
                                                                                                                                                                                                                                                                                                                                          marginTop: "8px",
                                                                                                                                                                                                                                                                                                                                                      marginBottom: "18px",
                                                                                                                                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                                                                                                                                        />

                                                                                                                                                                                                                                                                                                                                                                                <label>
                                                                                                                                                                                                                                                                                                                                                                                          <input
                                                                                                                                                                                                                                                                                                                                                                                                      type="checkbox"
                                                                                                                                                                                                                                                                                                                                                                                                                  checked={agree}
                                                                                                                                                                                                                                                                                                                                                                                                                              onChange={(e) => setAgree(e.target.checked)}
                                                                                                                                                                                                                                                                                                                                                                                                                                        />{" "}
                                                                                                                                                                                                                                                                                                                                                                                                                                                  I agree to receive quiz updates, offers, and announcements about future
                                                                                                                                                                                                                                                                                                                                                                                                                                                            EATABLE products via WhatsApp.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </label>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onClick={handleContinue}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        marginTop: "25px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    padding: "14px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                background: "#F57C00",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            color: "white",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        border: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    borderRadius: "10px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fontSize: "18px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Continue to Quiz
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </AppLayout>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }