import { useState } from "react";
import { useNavigate } from "react-router-dom";
import AppLayout from "../layouts/AppLayout";
import {
  isCooldownActive,
    getRemainingSeconds,
    } from "../services/cooldownService";
    import { saveSession } from "../services/sessionService";

    export default function Quiz() {
      const navigate = useNavigate();

        const [name, setName] = useState("");
          const [mobile, setMobile] = useState("");
            const [agree, setAgree] = useState(false);

              function handleContinue() {
                  if (name.trim().length < 3) {
                        alert("Please enter your name.");
                              return;
                                  }

                                      if (!/^[0-9]{10}$/.test(mobile)) {
                                            alert("Please enter a valid 10-digit mobile number.");
                                                  return;
                                                      }

                                                          if (!agree) {
                                                                alert(
                                                                        "Please agree to receive quiz updates, offers and announcements via WhatsApp."
                                                                              );
                                                                                    return;
                                                                                        }

                                                                                            if (isCooldownActive(mobile)) {
                                                                                                  const remaining = getRemainingSeconds(mobile);
                                                                                                        const minutes = Math.floor(remaining / 60);
                                                                                                              const seconds = remaining % 60;

                                                                                                                    alert(
                                                                                                                            `You can attempt the quiz again in ${minutes}:${seconds
                                                                                                                                      .toString()
                                                                                                                                                .padStart(2, "0")}.`
                                                                                                                                                      );
                                                                                                                                                            return;
                                                                                                                                                                }

                                                                                                                                                                    saveSession({
                                                                                                                                                                          name,
                                                                                                                                                                                mobile,
                                                                                                                                                                                      startedAt: Date.now(),
                                                                                                                                                                                          });

                                                                                                                                                                                              navigate("/play");
                                                                                                                                                                                                }

                                                                                                                                                                                                  return (
                                                                                                                                                                                                      <AppLayout title="Quiz Registration">
                                                                                                                                                                                                            <div style={{ padding: "20px" }}>
                                                                                                                                                                                                                    <h2>Quiz Registration</h2>

                                                                                                                                                                                                                            <label>Name</label>
                                                                                                                                                                                                                                    <input
                                                                                                                                                                                                                                              type="text"
                                                                                                                                                                                                                                                        value={name}
                                                                                                                                                                                                                                                                  onChange={(e) => setName(e.target.value)}
                                                                                                                                                                                                                                                                            placeholder="Enter your name"
                                                                                                                                                                                                                                                                                      style={{
                                                                                                                                                                                                                                                                                                  width: "100%",
                                                                                                                                                                                                                                                                                                              padding: "12px",
                                                                                                                                                                                                                                                                                                                          marginTop: "8px",
                                                                                                                                                                                                                                                                                                                                      marginBottom: "18px",
                                                                                                                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                                                                                                                        />

                                                                                                                                                                                                                                                                                                                                                                <label>Mobile Number</label>
                                                                                                                                                                                                                                                                                                                                                                        <input
                                                                                                                                                                                                                                                                                                                                                                                  type="tel"
                                                                                                                                                                                                                                                                                                                                                                                            value={mobile}
                                                                                                                                                                                                                                                                                                                                                                                                      onChange={(e) => setMobile(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                placeholder="10-digit mobile number"
                                                                                                                                                                                                                                                                                                                                                                                                                          style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                      width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                  padding: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                              marginTop: "8px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          marginBottom: "18px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <label style={{ display: "block", marginTop: "10px" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          type="checkbox"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      checked={agree}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onChange={(e) => setAgree(e.target.checked)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />{" "}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      I agree to receive quiz updates, offers, and announcements about future
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                EATABLE products via WhatsApp.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </label>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onClick={handleContinue}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            marginTop: "25px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        padding: "14px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    background: "#F57C00",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                color: "white",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            border: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        borderRadius: "10px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fontSize: "18px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Continue to Quiz
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </AppLayout>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }