import AppLayout from "../layouts/AppLayout";

export default function Quiz() {
  return (
      <AppLayout title="Quiz Registration">
            <div style={{ padding: "20px" }}>
                    <h2>Quiz Registration</h2>

                            <div style={{ marginTop: "20px" }}>
                                      <label>Name</label>
                                                <br />
                                                          <input
                                                                      type="text"
                                                                                  placeholder="Enter your name"
                                                                                              style={{
                                                                                                            width: "100%",
                                                                                                                          padding: "12px",
                                                                                                                                        marginTop: "8px",
                                                                                                                                                      marginBottom: "16px",
                                                                                                                                                                  }}
                                                                                                                                                                            />

                                                                                                                                                                                      <label>Mobile Number</label>
                                                                                                                                                                                                <br />
                                                                                                                                                                                                          <input
                                                                                                                                                                                                                      type="tel"
                                                                                                                                                                                                                                  placeholder="10-digit mobile number"
                                                                                                                                                                                                                                              style={{
                                                                                                                                                                                                                                                            width: "100%",
                                                                                                                                                                                                                                                                          padding: "12px",
                                                                                                                                                                                                                                                                                        marginTop: "8px",
                                                                                                                                                                                                                                                                                                      marginBottom: "16px",
                                                                                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                                                                                            />

                                                                                                                                                                                                                                                                                                                                      <label>
                                                                                                                                                                                                                                                                                                                                                  <input type="checkbox" /> I agree to receive quiz updates, offers,
                                                                                                                                                                                                                                                                                                                                                              and announcements about future EATABLE products via WhatsApp.
                                                                                                                                                                                                                                                                                                                                                                        </label>

                                                                                                                                                                                                                                                                                                                                                                                  <br />
                                                                                                                                                                                                                                                                                                                                                                                            <br />

                                                                                                                                                                                                                                                                                                                                                                                                      <button
                                                                                                                                                                                                                                                                                                                                                                                                                  style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                              padding: "14px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                            background: "#F57C00",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          color: "white",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        border: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      borderRadius: "10px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fontSize: "18px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Continue to Quiz
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </AppLayout>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }